name: Tests

on:
  push:
  pull_request:

jobs:
  build_and_push:
    name: Build Kubebuilder and Push to Dockerhub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      matrix:
        platform: ["linux"]
        version: ["v4.3.1"]
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          # e.g. kubebuilder:v4.3.1-linux
          tags: "${{ secrets.DOCKER_USERNAME }}/kubebuilder:${{ matrix.version }}-${{ matrix.platform }}"
